### ISSUE TITLE
No existe el atributo 'get_query_set'

### ISSUE THREAD

**Issue by Madh93** [tic-ull/dpCat#16]
Al ejecutar:

```
python manage.py publicar_video
```

Se obtiene el siguiente error:

> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/migue/Workspace/UDV/DPCAT/dpcatenv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 351, in execute_from_command_line
>     utility.execute()
>   File "/home/migue/Workspace/UDV/DPCAT/dpcatenv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 343, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/migue/Workspace/UDV/DPCAT/dpcatenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
>     self.execute(_args, *_cmd_options)
>   File "/home/migue/Workspace/UDV/DPCAT/dpcatenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
>     output = self.handle(_args, *_options)
>   File "/home/migue/Workspace/UDV/DPCAT/dpcatenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 661, in handle
>     return self.handle_noargs(**options)
>   File "/home/migue/Workspace/UDV/DPCAT/dpCat/yt_publisher/management/commands/publicar_video.py", line 17, in handle_noargs
>     pendings = list(Publicacion.objects.get_pendings())
>   File "/home/migue/Workspace/UDV/DPCAT/dpCat/yt_publisher/models.py", line 18, in get_pendings
>     return super(PublicacionManager, self).get_query_set().filter(status = 'PEN').order_by('id')
> AttributeError: 'super' object has no attribute 'get_query_set'

Django 1.8 ha renombrado 'get_query_set' por 'get_queryset':

https://docs.djangoproject.com/es/1.9/releases/1.8/
https://github.com/feincms/feincms/issues/548

**Comment by Madh93** [comment]
Mergeado :+1:
